### PR TITLE
Fix order of transparent objects

### LINKED ISSUE #258: Some texturing regressions
- Area indicators and arrows are untextured since #241 
- Interior of Enforcer have sides transparent, some textures missing since #241, fully transparent since #254
rwgame 2016-12-11 00-08-38-54
rwgame 2016-12-11 00-11-18-13
rwgame 2016-12-11 00-12-49-78

- Splash screens are missing since #254, because they are expected to be in 'generic' texture group, but  loaded into their own slots each.

### PR DESCRIPTION
**Pull request by ShFil119**
https://learnopengl.com/Advanced-OpenGL/Blending
suggests transparent objects should be last.
screenshot_20180317_141158

It should partially help with #258.

### CODE REVIEW

File: rwengine/src/render/GameRenderer.cpp [hunk 1]
```diff
@@ -357,7 +357,11 @@ void GameRenderer::renderWorld(GameWorld* world, const ViewCamera& camera,
     std::sort(renderList.begin(), renderList.end(),
               [](const Renderer::RenderInstruction& a,
                  const Renderer::RenderInstruction& b) {
-                  return a.sortKey < b.sortKey;
+                    if (!a.drawInfo.blend && b.drawInfo.blend) return true;
+                    if (!b.drawInfo.blend && a.drawInfo.blend) return false;
+                    if (a.sortKey > b.sortKey) return true;
```
Comment (danhedron) [inline rwengine/src/render/GameRenderer.cpp]: Won't this sort opaque objects into the wrong order?

Comment (ShFil119) [reply rwengine/src/render/GameRenderer.cpp]: ah, yes ;)

**Comment by darkf** [comment]
LGTM.
